version: "3.9"

volumes:
  envisage_news_data: {}

services:
  mongodb:
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - envisage_news_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password